### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by davelab6** [fontuni/fontuni#1]
Please add a license file to this project repository. I suggest using the SIL Open Font License, so that the code can only be used in other libre fonts :)

**Comment by sungsit** [comment]
Let’s discuss license strategy a little bit.

Ideally, I want more people to make more Thai fonts using F0ntUni as feature library which can be rendered quite consistently across well-known shaping engines (at least from my test). And in case they use this library to create commercial fonts, I also want them to have the right to sublicense their new fonts too (I’m thinking of individuals with less technical knowledge rather than big foundries).

So I think distribute feature source code under more permissive license like MIT would encourage new designers to create Thai fonts easier. As it aims to solve technical problems for Thai script and to support more [minority writing systems](http://scripts.sil.org/cms/scripts/page.php?item_id=ThaiLaoSeq&highlight=thai~minority) which have been ignored by almost all fonts for so long. So type designers could focus more on their design quality rather than hacking around with OpenType logic!

The sample face design of this project (UFO source or binary fonts) will be licensed under OFL anyway.

Is dual licensing the right move?

Another possible way to distribute this library is to make it as FontForge plugin or Python module for other font editors but I need to learn a lot more to do that. Basically, we need to create new encoding slot to cover Thai PUA glyphs, set glyph name or import namelist then import required features. We don’t need sample face for plugin so it could be GPLv3 like FontForge and can be used to make commercial fonts.

**Comment by davelab6** [comment]
> Thai PUA glyphs

Do you mean Thai unencoded glyphs, accessed via OpenType features, with glyph names following some convention?

**Comment by davelab6** [comment]
> I want more people to make more Thai fonts using F0ntUni as feature library ... I also want them to have the right to sublicense their new fonts too

If you want to permit restricted monopoly fonts to profit off your work without paying you, then this is okay. 

If you make it OFL, then you permit only libre font developers to profit off your work without paying you, and you require restricted monopoly font developers to contact you to purchase a license permitting them to include the otherwise OFL code in their fonts. 

Often this business model is 'implicit' and its so common in the software world that it goes without saying; but you could advertise that this is how the business model works explicitly if you think the thai type design market is not savvy enough to understand how it works.

**Comment by davelab6** [comment]
> then import required features

Since the plugin would copy parts of itself into the resulting fonts, those fonts are 'derived works' under copyright and thus subject to the terms of the plugin's license - just the same as if you copied parts of a example project into your own project by hand

**Comment by sungsit** [comment]
You’ve convinced me to go OFL. It’s not that Thai market wouldn’t understand 'implicit' model. It’s just me who always see my open source projects as a playground not a potential business, in terms of getting paid by doing something fun! Thank you for 'implicitly' make me realise that I may underestimate my own works!

I have nothing against OFL as long as it’s good for libre font developers and I think I could selectively permit someone to sublicense their derived works without paying me, a student who wants to make new fonts for extra income for some good reasons, for example. OFL can achieve my ideal.

> Thai PUA glyphs

I meant positional variants from [vender’s glyph extension that supported by HarfBuzz](https://github.com/behdad/harfbuzz/blob/master/src/hb-ot-shape-complex-thai.cc#L93). There’re 2 sets though, Windows PUA vs Mac PUA. Basically, people can use those code points to make thai font works out-of-the-box without any features, in case of Linux desktop and modern web browsers. I'm using Mac PUA set for F0ntUni as it has [Adobe’s legacy glyph names](https://github.com/adobe-type-tools/agl-aglfn/blob/master/glyphlist.txt#L2586) for referencing reason.

If you have a time to check it out, new F0ntUni has 3 feature sets currently. Bare & Extended sets have positional variants and Extended set also supports minority language. Basic set is almost without positional variants, instead of doing glyph substitute it's using `mark` & `mkmk` features intensively.

I’ll spend some time on documenting how the library works later.
